# Generated by Django 5.1.4 on 2026-05-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_message_message_type_alter_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='account.booking'),
        ),
    ]
