from django.urls import path
from .views import register_user, login_user, logout_user, skill_list_create, skill_detail, match_list, connect_user, notification_list, respond_to_connection, get_conversations, get_messages, send_message, create_booking, get_bookings, respond_to_booking, update_booking_status, get_dashboard_data, user_profile, admin_dashboard_data, admin_users_list, mark_booking_done, request_booking_cancellation, respond_to_cancellation, submit_report, get_admin_support_info, send_support_message
from .admin_views import AdminStatsView, AdminLiveActivityView, AdminTopUsersView, AdminUserGrowthView, AdminRecentTransactionsView, AdminAllSwapsView, AdminReportListView, AdminReportActionView, AdminSupportConversationsView, AdminSupportMessagesView, AdminSendSupportMessageView

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('skills/', skill_list_create, name='skill-list'),
    path('skills/<int:pk>/', skill_detail, name='skill-detail'),
    path('matches/', match_list, name='match-list'),
    path('connect/', connect_user, name='connect-user'),
    path('connect/respond/', respond_to_connection, name='respond-connection'),
    path('notifications/', notification_list, name='notification-list'),
    path('conversations/', get_conversations, name='get-conversations'),
    path('messages/', get_messages, name='get-messages'),
    path('messages/send/', send_message, name='send-message'),
    path('bookings/create/', create_booking, name='create-booking'),
    path('bookings/', get_bookings, name='get-bookings'),
    path('bookings/respond/', respond_to_booking, name='respond-booking'),
    path('bookings/update/', update_booking_status, name='update-booking-status'),
    path('bookings/mark-done/', mark_booking_done, name='mark-booking-done'),
    path('bookings/request-cancellation/', request_booking_cancellation, name='request-booking-cancellation'),
    path('bookings/respond-cancellation/', respond_to_cancellation, name='respond-cancellation'),
    path('dashboard-data/', get_dashboard_data, name='dashboard-data'),
    path('profile/', user_profile, name='user-profile'),
    path('reports/submit/', submit_report, name='submit-report'),
    path('support/admin-info/', get_admin_support_info, name='support-admin-info'),
    path('support/send/', send_support_message, name='support-send-message'),
    path('admin/dashboard/', admin_dashboard_data, name='admin-dashboard'),
    path('admin/users/', admin_users_list, name='admin-users'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/live-activity/', AdminLiveActivityView.as_view(), name='admin-live-activity'),
    path('admin/top-users/', AdminTopUsersView.as_view(), name='admin-top-users'),
    path('admin/user-growth/', AdminUserGrowthView.as_view(), name='admin-user-growth'),
    path('admin/recent-transactions/', AdminRecentTransactionsView.as_view(), name='admin-recent-transactions'),
    path('admin/swaps/', AdminAllSwapsView.as_view(), name='admin-swaps'),
    path('admin/reports/', AdminReportListView.as_view(), name='admin-reports'),
    path('admin/reports/<int:report_id>/action/', AdminReportActionView.as_view(), name='admin-report-action'),
    path('admin/support/conversations/', AdminSupportConversationsView.as_view(), name='admin-support-conversations'),
    path('admin/support/messages/<int:user_id>/', AdminSupportMessagesView.as_view(), name='admin-support-messages'),
    path('admin/support/send/', AdminSendSupportMessageView.as_view(), name='admin-send-support-message'),
]